best_params_dict = {'Cora':  {'add_source': True, 'adjoint': False, 'adjoint_method': 'adaptive_heun', 'adjoint_step_size': 1, 'alpha': 1.0,
   'alpha_dim': 'sc', 'att_samp_pct': 1, 'attention_dim': 128, 'attention_norm_idx': 1, 'attention_rewiring': False,
   'attention_type': 'scaled_dot', 'augment': False, 'baseline': False, 'batch_norm': False, 'beltrami': True,
   'beta_dim': 'sc', 'block': 'attention', 'cpus': 1, 'data_norm': 'rw', 'dataset': 'Cora',
   'decay': 0.00507685443154266, 'directional_penalty': None, 'dropout': 0.046878964627763316,
   'dt_min': 1e-05, 'epoch': 100, 'exact': True, 'fc_out': False, 'feat_hidden_dim': 64, 'function': 'laplacian',
   'gdc_avg_degree': 64, 'gdc_k': 64, 'gdc_method': 'ppr', 'gdc_sparsification': 'topk', 'gdc_threshold': 0.01,
   'gpus': 0.5, 'grace_period': 20, 'heads': 8, 'heat_time': 3.0, 'hidden_dim': 80, 'input_dropout': 0.5,
   'jacobian_norm2': None, 'kinetic_energy': None, 'label_rate': 0.5, 'leaky_relu_slope': 0.2,
   'lr': 0.022924849756740397, 'max_epochs': 1000, 'max_iters': 100, 'max_nfe': 2000, 'method': 'dopri5',
   'metric': 'accuracy', 'mix_features': False, 'name': 'cora_beltrami_splits', 'new_edges': 'random',
   'no_alpha_sigmoid': False, 'not_lcc': True, 'ode_blocks': 1,
   'optimizer': 'adamax', 'pos_enc_hidden_dim': 16, 'pos_enc_orientation': 'row',
   'pos_enc_type': 'GDC', 'ppr_alpha': 0.05, 'reduction_factor': 10, 'regularise': False, 'reweight_attention': False,
   'rewiring': None, 'self_loop_weight': 1, 'square_plus': True,
   'step_size': 1, 'time': 18.294754260552843, 'tol_scale': 821.9773048827274,
   'tol_scale_adjoint': 1.0, 'total_deriv': None, 'use_cora_defaults': False, 'use_flux': False, 'use_labels': False,
   'use_lcc': True, 'use_mlp': False},
   'Citeseer':{},
   'Pubmed':{}}